modLoader = "kotlinforforge"
loaderVersion = "[6,)"
license = "MIT"
issueTrackerURL = "https://github.com/GaborWnuk/WingedSandals/issues"

[[mods]]
modId = "wingedsandals"
version = "${version}"
displayName = "WingedSandals"
displayURL = "https://github.com/GaborWnuk/WingedSandals"
logoFile = "assets/wingedsandals/icon.png"
authors = "adil192, GaborWnuk"
description = '''Special boots that give you creative-style flight'''

[[dependencies.wingedsandals]]
modId = "neoforge"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wingedsandals]]
modId = "minecraft"
type = "required"
versionRange = "${minecraftVersionRange}"
ordering = "NONE"
side = "BOTH"

[[dependencies.wingedsandals]]
modId = "kotlinforforge"
type = "required"
versionRange = "[6.3.0,)"
ordering = "NONE"
side = "BOTH"
